import type { LucideIcon } from "lucide-react";
import {
  LayoutDashboard,
  BarChart3,
  Users,
  TrendingUp,
  Dice5,
  Gift,
  Share2,
  FileSearch,
  Shield,
  Wallet,
  ListOrdered,
  ImageIcon,
  Building2,
  ArrowDownToLine,
  Coins,
  Bell,
  FolderCog,
} from "lucide-react";

export type CommandPaletteRoute = {
  id: string;
  href: string;
  title: string;
  description: string;
  Icon: LucideIcon;
  /** Extra strings to match when searching */
  keywords?: string[];
};

/** Default + common pages — searchable from header command palette */
export const COMMAND_PALETTE_ROUTES: CommandPaletteRoute[] = [
  {
    id: "dashboard",
    href: "/dashboard",
    title: "Dashboard",
    description: "Get full information about current system status",
    Icon: LayoutDashboard,
    keywords: ["home", "main"],
  },
  {
    id: "dashboard-charts",
    href: "/dashboard/analytics",
    title: "Dashboard: Charts",
    description: "View charts of current system status",
    Icon: BarChart3,
    keywords: ["analytics", "stats", "ggr"],
  },
  {
    id: "players",
    href: "/players",
    title: "Players",
    description: "View all players",
    Icon: Users,
    keywords: ["users", "downline"],
  },
  {
    id: "bonus-root",
    href: "/bonus/bonus",
    title: "Bonus",
    description: "Account statement and bonus-related reports",
    Icon: Gift,
    keywords: ["statement", "account"],
  },
  {
    id: "transactions-request",
    href: "/transactions/requests",
    title: "Transactions: Request",
    description: "Deposit and withdraw requests",
    Icon: Wallet,
    keywords: ["deposit", "withdraw", "requests"],
  },
  {
    id: "transactions-request-withdraw",
    href: "/transactions/requests/withdraw",
    title: "Transactions: Withdraw request",
    description: "Withdraw requests",
    Icon: Wallet,
    keywords: ["payout", "withdrawal"],
  },
  {
    id: "transactions-auto",
    href: "/accounts/deposit",
    title: "Transactions: Auto",
    description: "Auto deposit",
    Icon: ArrowDownToLine,
  },
  {
    id: "transactions-manual",
    href: "/accounts/withdraw",
    title: "Transactions: Manual",
    description: "Manual withdraw",
    Icon: Wallet,
  },
  {
    id: "sports-betlist",
    href: "/sports/betlist",
    title: "Sports: Betlist",
    description: "Bet history and list",
    Icon: ListOrdered,
    keywords: ["bets", "history", "sports"],
  },
  {
    id: "sports-spm",
    href: "/sports/spm-sports",
    title: "Sports: SPM Sports",
    description: "Sports markets (SPM)",
    Icon: TrendingUp,
    keywords: ["markets", "spm"],
  },
  {
    id: "sports-betfair",
    href: "/sports/betfair",
    title: "Sports: Betfair",
    description: "Sports markets (Betfair)",
    Icon: TrendingUp,
    keywords: ["markets", "betfair"],
  },
  {
    id: "sports-betby",
    href: "/sports/betby",
    title: "Sports: Betby",
    description: "Sports markets (Betby)",
    Icon: TrendingUp,
    keywords: ["markets", "betby"],
  },
  {
    id: "sports-atlas",
    href: "/sports/atlas",
    title: "Sports: Atlas",
    description: "Sports markets (Atlas)",
    Icon: TrendingUp,
    keywords: ["markets", "atlas"],
  },
  {
    id: "sports-ig-pixel",
    href: "/sports/ig-pixel",
    title: "Sports: IG Pixel",
    description: "Sports markets (IG Pixel)",
    Icon: TrendingUp,
    keywords: ["markets", "ig", "pixel"],
  },
  {
    id: "sports-alt-gaming",
    href: "/sports/alt-gaming",
    title: "Sports: Alt Gaming",
    description: "Sports markets (Alt Gaming)",
    Icon: TrendingUp,
    keywords: ["markets", "alt", "gaming"],
  },
  {
    id: "casino-stats",
    href: "/casino/stats",
    title: "Casino: Stats",
    description: "Casino analytics",
    Icon: BarChart3,
    keywords: ["security", "analytics"],
  },
  {
    id: "casino-bet-list",
    href: "/casino/bet-list",
    title: "Casino: Bet List",
    description: "Casino bet history",
    Icon: ListOrdered,
    keywords: ["bets", "history", "casino"],
  },
  {
    id: "casino-games",
    href: "/casino/games",
    title: "Casino: Games",
    description: "Manage markets / games",
    Icon: Dice5,
    keywords: ["markets", "manage"],
  },
  {
    id: "bonus-statment",
    href: "/bonus/statment",
    title: "Bonus: Statment",
    description: "Credit statement",
    Icon: FileSearch,
    keywords: ["statement"],
  },
  {
    id: "bonus-claims",
    href: "/bonus/claims",
    title: "Bonus: Claims",
    description: "Downline summary",
    Icon: Share2,
  },
  {
    id: "referrals",
    href: "/referrals",
    title: "Referrals",
    description: "Referral settings",
    Icon: Share2,
    keywords: ["referral"],
  },
  {
    id: "settings-root",
    href: "/settings",
    title: "Settings",
    description: "Application settings",
    Icon: FolderCog,
    keywords: ["preferences"],
  },
  {
    id: "wallets",
    href: "/wallets",
    title: "Wallets",
    description: "Balance and wallets",
    Icon: Wallet,
    keywords: ["balance", "currency"],
  },
  {
    id: "website-analytics",
    href: "/website/analytics",
    title: "Website: Analytics",
    description: "Site analytics",
    Icon: BarChart3,
  },
  {
    id: "website-banners",
    href: "/website/banners",
    title: "Website: Banners",
    description: "Manage banners",
    Icon: ImageIcon,
  },
  {
    id: "website-banking",
    href: "/website/banking",
    title: "Website: Banking",
    description: "Account history / banking",
    Icon: Building2,
  },
  {
    id: "website-gateways",
    href: "/website/gatways",
    title: "Website: Gateways",
    description: "Deposit gateways",
    Icon: Coins,
  },
  {
    id: "website-currency",
    href: "/website/currency",
    title: "Website: Currency",
    description: "Balance and currency",
    Icon: Coins,
  },
  {
    id: "website-forms",
    href: "/website/forms",
    title: "Website: Forms",
    description: "Notifications and forms",
    Icon: Bell,
  },
  {
    id: "website-external",
    href: "/website/external-integrations",
    title: "Website: External Integrations",
    description: "Event types and integrations",
    Icon: FolderCog,
  },
  {
    id: "website-data",
    href: "/website/data-integrations",
    title: "Website: Data Integrations",
    description: "Data integrations",
    Icon: FolderCog,
  },
  {
    id: "reports",
    href: "/reports/profit-loss",
    title: "Reports: Profit & Loss",
    description: "Profit & loss",
    Icon: FileSearch,
    keywords: ["reports", "p&l"],
  },
  {
    id: "reports-losing-commission",
    href: "/players/detail",
    title: "Reports: Losing Commission",
    description: "Player detail / losing commission",
    Icon: FileSearch,
  },
  {
    id: "reports-blocked-players",
    href: "/players/blocked",
    title: "Reports: Blocked Players",
    description: "Blocked players",
    Icon: FileSearch,
  },
  {
    id: "reports-blocked-history",
    href: "/players/blocked-history",
    title: "Reports: Blocked Player History",
    description: "Blocked player history",
    Icon: FileSearch,
  },
  {
    id: "reports-demo-players",
    href: "/players/demo",
    title: "Reports: Demo Players",
    description: "Demo players",
    Icon: FileSearch,
  },
  {
    id: "reports-nth-deposit",
    href: "/players/nth-deposit",
    title: "Reports: Nth Deposit",
    description: "Nth deposit players",
    Icon: FileSearch,
  },
  {
    id: "reports-ftd",
    href: "/players/ftd",
    title: "Reports: FTD",
    description: "First-time deposit players",
    Icon: FileSearch,
  },
  {
    id: "reports-zero-deposit",
    href: "/players/zero-deposit",
    title: "Reports: Zero Deposit Players",
    description: "Zero deposit players",
    Icon: FileSearch,
  },
  {
    id: "reports-inactive",
    href: "/players/inactive",
    title: "Reports: Inactive Players",
    description: "Inactive players",
    Icon: FileSearch,
  },
  {
    id: "reports-player-master",
    href: "/players/master",
    title: "Reports: Player Master",
    description: "Player master",
    Icon: FileSearch,
  },
  {
    id: "user-groups-login-history",
    href: "/security/login-history",
    title: "User Groups: User Groups",
    description: "Login history",
    Icon: Shield,
    keywords: ["security", "sessions"],
  },
  {
    id: "user-groups-flags",
    href: "/players/blocked-history",
    title: "User Groups: Flags",
    description: "Flags (blocked history)",
    Icon: Shield,
    keywords: ["flags", "blocked"],
  },
  {
    id: "security-roles",
    href: "/security/token-history",
    title: "Security: Roles",
    description: "Roles & token history",
    Icon: Shield,
    keywords: ["tokens"],
  },
  {
    id: "security-fraud-logs",
    href: "/security/token-history",
    title: "Security: Fraud Logs",
    description: "Fraud logs (token history)",
    Icon: Shield,
    keywords: ["fraud"],
  },
  {
    id: "security-activity",
    href: "/security/activity",
    title: "Security: Activity",
    description: "Activity logs",
    Icon: Shield,
  },
  {
    id: "profile",
    href: "/profile",
    title: "My Profile",
    description: "Your profile settings",
    Icon: Users,
  },
];

export function filterCommandRoutes(
  query: string,
  routes: CommandPaletteRoute[] = COMMAND_PALETTE_ROUTES,
): CommandPaletteRoute[] {
  const q = query.trim().toLowerCase();
  if (!q) return routes;
  return routes.filter((r) => {
    const hay = [
      r.title,
      r.description,
      r.href,
      ...(r.keywords ?? []),
    ]
      .join(" ")
      .toLowerCase();
    return hay.includes(q) || q.split(/\s+/).every((word) => hay.includes(word));
  });
}
